#define MAX_CONFIGS 4
#define MAX_HEADS 16
#define MAX_BLOCKS 128
#define MAX_SETTINGS 32
#define MAX_STR_LEN 2048
#define MAX_ERRORS 1024
#define MAX_CRYSTALS_X 16
#define MAX_CRYSTALS_Y 16
#define MAX_CRYSTALS (MAX_CRYSTALS_X * MAX_CRYSTALS_Y)
#define MAX_HEAD_CRYSTALS MAX_BLOCKS*MAX_CRYSTALS
#define MAX_HEAD_VERTICES MAX_BLOCKS*((2*16)+1)*((2*16)+1)
#define MAX_TOTAL_BLOCKS MAX_HEADS*MAX_BLOCKS

#define SCANNER_P39 0
#define SCANNER_PETSPECT 1
#define SCANNER_HRRT 2
#define SCANNER_P39_IIA 3
#define SCANNER_RING 4

#define PMTA 0
#define PMTB 1
#define PMTC 2
#define PMTD 3
#define CFD 4
#define CFD_DELAY 5
#define X_OFFSET 6
#define Y_OFFSET 7
#define E_OFFSET 8
#define DHI_MODE 9
#define SETUP_ENG 10
#define SHAPE 11
#define SLOW_LOW 12
#define SLOW_HIGH 13
#define FAST_LOW 14
#define FAST_HIGH 15
#define CFD_SETUP 16
#define TDC_GAIN 17
#define TDC_OFFSET 18
#define TDC_SETUP 19
#define CFD_ENERGY_0 20
#define CFD_ENERGY_1 21
#define PEAK_STDEV 22
#define PHOTOPEAK 23
#define SETUP_TEMP 24

#define NUM_DHI_MODES 9
#define DHI_MODE_POSITION_PROFILE 0
#define DHI_MODE_CRYSTAL_ENERGY 1
#define DHI_MODE_TUBE_ENERGY 2
#define DHI_MODE_SHAPE_DISCRIMINATION 3
#define DHI_MODE_RUN 4
#define DHI_MODE_TRANSMISSION 5
#define DHI_MODE_SPECT 6
#define DHI_MODE_TIME 7
#define DHI_MODE_TEST 8
#define DATA_MODE_TIMING NUM_DHI_MODES
#define DATA_MODE_COINC_FLOOD (NUM_DHI_MODES+1)

#define NUM_LAYER_TYPES 3
#define LAYER_FAST 0
#define LAYER_SLOW 1
#define LAYER_ALL 2

#define NUM_ZAP_TYPES 4
#define ZAP_ALL 0
#define ZAP_ANALOG_SETTINGS 1
#define ZAP_TIME 2
#define ZAP_ENERGY 3

#define NUM_RAM_TYPES 4
#define RAM_ENERGY_PEAKS 0
#define RAM_TIME_OFFSETS 1
#define RAM_ANALOG_SETTINGS 2
#define RAM_PEAK_LOCATIONS 3

#define RETRY 1
#define NORETRY 0

#define SYNC_PROBLEM 1
#define CODE_PROBLEM 2
#define INPUT_PROBLEM 3
#define TIMEOUT_PROBLEM 4
#define IO_PROBLEM 5
#define CHECKSUM_PROBLEM 6
#define SERVER_LOCKED_PROBLEM 7
#define UNKNOWN_CODE_PROBLEM 8
#define NOT_INITIALIZED_PROBLEM 9
#define UNKNOWN_SCANNER_PROBLEM 10
#define NOT_IMPLEMENTED_PROBLEM 11
#define MEMORY_PROBLEM 12

#define PORT_ETHERNET 0
#define PORT_SERIAL 1
#define PORT_SIMULATION 2
#define PORT_GCI 3

#define NUM_CP_MODES 5
#define CP_MODE_COINC 0
#define CP_MODE_PASSTHRU 1
#define CP_MODE_TAG 2
#define CP_MODE_TEST 3
#define CP_MODE_TIME 4

#define ALL_BLOCKS -1
#define NO_BLOCKS -2

#define WAIT_COINC 64
#define WAIT_ALL_HEADS -1
#define WAIT_EVERYTHING -2

#define SINGLES_CFD 0
#define SINGLES_VALIDS 1

#define NUM_HEAD_TYPES 5
#define HEAD_TYPE_LSO_LSO 0
#define HEAD_TYPE_LSO_NAI 1
#define HEAD_TYPE_LSO_ONLY 2
#define HEAD_TYPE_GSO_LSO 3
#define HEAD_TYPE_LYSO_LSO 4

#define ACQUISITION_SECONDS 0
#define ACQUISITION_BLOCKS 1

#define SCAN_EM 0
#define SCAN_EMTX 1
#define SCAN_TX 2
