# Generated automatically from Makefile.in by configure.

 # -D _GLIBCXX_USE_CXX11_ABI=0
CFLAGS = -g -O2
CC = gcc
LIBS = -lm 


all: library align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer

library:
	cd src; ${MAKE} libRPW.a "CFLAGS=${CFLAGS}"

align_warp: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
alignlinear: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
binarize: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
binarymask: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
binarymath: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
cd_air: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
cd_warp: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
combine_air: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
combine_warp: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
crop: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
definecommon_air: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
determinant_mask: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
fixheader: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
fuse: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
gsmooth: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
identify: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
invert_air: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
layout: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
magnify: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
makeaheader: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
manualreslice: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
mv_air: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
mv_warp: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
overlay_mask: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reconcile_air: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reorient: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
resize: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_ucf: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_unwarp: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_unwarp_ucf: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_vector: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_warp: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reslice_warp_ucf: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
reunite: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
scan_vector: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
scan_warp: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
scanair: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
scanheader: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
separate: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
setheadermax: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
sizeof: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
softmean: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
softmeannorescale: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
straightmean: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
straightmeannorescale: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
strictmean: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
strictmeannorescale: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
zoomer: library
	${CC} ${@}.c -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}


# Not all version of make support an empty suffix rule
# Therefore this empty suffix rule is provided for convenience only
# It is not required or used for compiling the standard AIR distribution
.c :
	${CC} $< -o $@ -Lsrc -lRPW ${LIBS} ${CFLAGS}
	
clean:
	cd src; ${MAKE} clean
	rm -f align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer
	rm -f config.cache config.log config.status
	cd bin; rm -f align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer

	
install:
	mv align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer bin
	
distclean:
	cd src; ${MAKE} distclean
	rm -f align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer
	rm -f config.cache config.log config.status
	rm -f Makefile
	cd bin; rm -f align_warp alignlinear binarize binarymask binarymath cd_air cd_warp combine_air combine_warp crop definecommon_air determinant_mask fixheader fuse gsmooth identify invert_air layout magnify makeaheader manualreslice mv_air mv_warp overlay_mask reconcile_air reorient resize reslice reslice_ucf reslice_unwarp reslice_unwarp_ucf reslice_vector reslice_warp reslice_warp_ucf reunite scan_vector scan_warp scanair scanheader separate setheadermax sizeof softmean softmeannorescale straightmean straightmeannorescale strictmean strictmeannorescale zoomer
	
	

