
#include <stdio.h>
#include "ecodes.h"

static char *e_short_text[] =
{
	"OK - Operation Completed Correctly",
   "E_CHANNEL_OOR - Channel is out of range",
   "E_PARAMETER_OOR - Parameter is out of range",
   "E_UNKNOWN_PARAMETER - Unknown parameter",
   "E_NO_CONFIG - Configuration out of range (0-3)",
   "E_NO_MODE - Mode not recognized",
   "E_WRITE_FAILED - Write to flash disk failed (disk full?)",
   "E_OPEN_FAILED - Open failed, file not found",
   "E_BAD_FORMAT - Can't interpret data due to unrecognized formatting",
   "E_PRIORITY_FAILED - Download to priority device failed",
   "E_ANALOG_FAILED - Download to analog subsection failed",
   "E_ANALOG_COMM - Communication with analog subsection failed",
   "E_CHECKSUM - Checksum error occured during upload/download",
   "E_CMD_IN_PROGRESS - Background command is already in progress",
   "E_UNKNOWN_LOAD_TYPE - Data load type specified is not recognized",
   "E_SYNTAX_ERROR - Cannot interpret command, required parameters missing",
   "E_UNKNOWN_CMD - Unrecognized command",
   "E_TIMED_OUT - Command timed out",
   "E_E2POT_READ_FAILED - Cannot read EEPOT on HRRT detector head",
   "E_E2POT_WRITE_FAILED - Cannot write EEPOT on HRRT detector head",
   "E_E2POT_TRANSFER_FAILED - Cannot transfer temporary value to long term storage",
   "E_DIAG_TIMED_OUT - Diagnostic/Alignment routine did not complete in time",
   "E_XY_OFFSET_OOR - X or Y offset is not within range for proper function",
   "E_DELAY_OOR - CFD Delay is not within range for proper function",
   "E_ANALOG_DIAG_FAILED - Analog Processor diagnostics failed",
   "E_HIGH_VOLTAGE_ON - High Voltage is on when it should be off",
   "E_HIGH_VOLTAGE_OFF - High Voltage is off when it should be on",
   "E_VOLTAGE_LOW - Supply voltage is low",
   "E_PI_OVER_TEMP - Panel Interface is over the maximum permitted temperature",
   "E_DETECTOR_OVER_TEMP - Detector is over the maximum permitted temperature",
   "E_PI_REF_WRITE_FAILED - Panel reference save failed (Is write protection on?)",
   "E_PI_VOLTAGE_FAILED - Hardware failure reading Panel Interface voltage",
   "E_PI_TEMP_FAILED - Hardware failure reading Panel Interface temperature",
   "E_EOF - End of File",
   "E_DHI_LOW_TEMP - Detector Head Interface temperature too low",
   "E_DHI_HIGH_TEMP - Detector Head Interface temperature too high",
   "E_MEMORY - Unable to allocate enough memory to proceed with operation",
   "E_READ_FAILED - Read from flash disk failed",
   "E_CC_DOWNLOAD_ERROR - Error downloading to Coincidence Controller FPGAs",
   "E_CC_SINGLES_TIMEOUT - Coincidence Controller timed out reading singles rates from Detector Head Interface",
   "E_CC_TEMP_TIMEOUT - Coincidence Controller timed out reading temperature from Detector Head Interface",
   "E_PS_AXIAL_FAILURE - Unable to communicate with pointsource axial controller",
   "E_PS_TRANS_FAILURE - Unable to communicate with pointsource transaxial controller",
   "E_PS_AXIAL_JAMMED - Pointsource axial servo is not where it is supposed to be",
   "E_PS_TRANS_JAMMED - Pointsource transaxial servo is not where it is supposed to be",
   "E_PS_MOTION_NOT_AT_REST - Pointsource is currently moving and must be stopped before issuing another move command",
   "E_PS_GENERAL_FAILURE - Unable to do anything with pointsource motion control hardware",
   "E_PS_MOTION_ALREADY_AT_REST - Pointsource motion cannot be stopped if it is already stopped",
   "E_ORDER - Parameters are out of order",
   "E_LIMIT_OOR - Energy limits out of range (0-1000)",
   "E_FNF - File not found",
   "E_CC_REBOOT - Coincidence Controller has rebooted",
   "E_CC_BUCKET_COMM - Unable to communicate with detector head interface",
   "E_CC_HW_FAILURE - Coincidence Controller hardware not responding to commands",
   "E_ESTOP - System has been put in emergency stop",
   "E_NO_SCAN - A scan must be configured before it is started",
   "E_SCAN_IN_PR0GRESS - A scan is already running and must be stopped before it can be reconfigured",
   "E_PS_NO_EXTEND - Pointsource did not extend",
   "E_PS_NO_RETRACT - Pointsource did not retract",
   "E_COMM_ERROR - Unable to initialize UART to communicate serially",
   "E_RAMTEST_FAILED - Analog subsection RAM test failed for one or more channels",
   "E_SHUTDOWN - System is in shutdown state due to temperatures out of range",
   "E_PS_AXIAL_MISALIGNED - Pointsource is misaligned in the axial direction",  // -62
   "E_PS_TRANS_MISALIGNED - Pointsource is misaligned in the transaxial direction",  // -63
   "E_UNKNOWN_CODE_64 (RESERVED)",
   "E_UNKNOWN_CODE_65 (RESERVED)",
   "E_UNKNOWN_CODE_66 (RESERVED)",
   "E_UNKNOWN_CODE_67 (RESERVED)",
   "E_UNKNOWN_CODE_68 (RESERVED)",
   "E_UNKNOWN_CODE_69 (RESERVED)",
   "E_UNKNOWN_CODE_70 (RESERVED)",
   "E_UNKNOWN_CODE_71 (RESERVED)",
   "E_UNKNOWN_CODE_72 (RESERVED)",
   "E_UNKNOWN_CODE_73 (RESERVED)",
   "E_UNKNOWN_CODE_74 (RESERVED)",
   "E_UNKNOWN_CODE_75 (RESERVED)",
   "E_UNKNOWN_CODE_76 (RESERVED)",
   "E_UNKNOWN_CODE_77 (RESERVED)",
   "E_UNKNOWN_CODE_78 (RESERVED)",
   "E_UNKNOWN_CODE_79 (RESERVED)",
   "E_UNKNOWN_CODE_80 (RESERVED)",
   "E_UNKNOWN_CODE_81 (RESERVED)",
   "E_UNKNOWN_CODE_82 (RESERVED)",
   "E_UNKNOWN_CODE_83 (RESERVED)",
   "E_UNKNOWN_CODE_84 (RESERVED)",
   "E_UNKNOWN_CODE_85 (RESERVED)",
   "E_UNKNOWN_CODE_86 (RESERVED)",
   "E_UNKNOWN_CODE_87 (RESERVED)",
   "E_UNKNOWN_CODE_88 (RESERVED)",
   "E_UNKNOWN_CODE_89 (RESERVED)",
   "E_UNKNOWN_CODE_90 (RESERVED)",
   "E_UNKNOWN_CODE_91 (RESERVED)",
   "E_UNKNOWN_CODE_92 (RESERVED)",
   "E_UNKNOWN_CODE_93 (RESERVED)",
   "E_UNKNOWN_CODE_94 (RESERVED)",
   "E_UNKNOWN_CODE_95 (RESERVED)",
   "E_UNKNOWN_CODE_96 (RESERVED)",
   "E_UNKNOWN_CODE_97 (RESERVED)",
   "E_UNKNOWN_CODE_98 (RESERVED)",
   "E_UNKNOWN_CODE_99 (RESERVED)",
   "E_UNKNOWN_CODE_100 (RESERVED)",
   "E_1 - Error downloading pc_sd1.rbf file to interface device",
	"E_2 - Error Test_SIN_SOUT(INTERFACE_DEVICE)",
	"E_3 - Error Test_PC104_Interface()",
	"E_4 - Error downloading pc_run.rbf to INTERFACE_DEVICE",
	"E_5 - Error Test_Temperature_Sensors()",
	"E_6 - Error downloading pe_sd1.rbf to PRIORITY_END_DEVICE",
	"E_7 - Error Test_SIN_SOUT(PRIORITY_END_DEVICE)",
	"E_8 - Error downloading pe_sd3.rbf to PRIORITY_END_DEVICE",
	"E_9 - Error Test_Priority_End_Device()",
	"E_10 - Error downloading pr_sd1.rbf to PRIORITY_DEVICE",
	"E_11 - Error Test_SIN_SOUT(PRIORITY_DEVICE)",
	"E_12 - Error downloading pr_sd3.rbf to PRIORITY_DEVICE",
	"E_13 - Error downloading pe_sd6.rbf PRIORITY_END_DEVICE",
	"E_14 - Error Test_Priority_Serial_Lines",
	"E_15 - Error downloading pe_sd2.rbf to PRIORITY_END_DEVICE",
	"E_16 - Error Perform_Priority_Diagnostics",
	"E_17 - Error Test_DIP_Switch()",
	"E_18 - Error downloading pr_ld.rbf to PRIORITY_DEVICE",
	"E_19 - Error downloading as_sd0.rbf to ANALOG_SUBSECTION_DEVICE",
	"E_20 - Error downloading as_sd1.rbf to ANALOG_SUBSECTION_DEVICE",
	"E_21 - Error downloading pr_sd2.rbf to PRIORITY_DEVICE",
	"E_22 - Error Perform_AS_Diagnostics",
	"E_23 - Error  downloading as_sd2.rbf to ANALOG_SUBSECTION_DEVICE",
   "E_24 - Error Test_Clk_Sync (ANALOG_SUBSECTION_DEVICE)",
	"E_25 - Error downloading as_clk.rbf to ANALOG_SUBSECTION_DEVICE",
	"E_26 - Error downloading pr_sd4.rbf to PRIORITY_DEVICE",
	"E_27 - Error Test_Clk_Sync(PRIORITY_DEVICE)",
	"E_28 - Error downloading pi_sd1.rbf to PANEL_INTERFACE_DEVICE",
	"E_29 - Error Test_SIN_SOUT(PANEL_INTERFACE_DEVICE",
	"E_30 - Error downloading pi_run.rbf to PANEL_INTERFACE_DEVICE",
	"E_31 - Error Initialize_PI_Reference_Voltage()",
	"E_32 - Error Test_Panel_Interface_Supply_Voltage()",
	"E_33 - Error downloading pr_run.rbf to PRIORITY_DEVICE",
	"E_34 - Error downloading pe_sd5.rbf to PRIORITY_END_DEVICE",
	"E_35 - Error Test_Clk_Sync(PRIORITY_END_DEVICE)",
	"E_36 - Error downloading pe_sd4.rbf to PRIORITY_END_DEVICE",
	"E_37 - Error downloading AS_rmtst.rbf to ANALOG_SUBSECTION_DEVICE",
	"E_38 - Error downloading pr_set.rbf to PRIORITY_DEVICE",
	"E_39 - Error performing BIST RAM test",
	"E_40 - Error downloading as_setup.rbf to ANALOG_SUBSECTION_DEVICE",
	"E_41 - Error downloading as_tmd.rbf to ANALOG_SUBSECTION_DEVICE",
	"E_42 - Error performing TMD test"
};

static char e_buf[128];

char *error_description(int ecode)
{
   if (ecode <= 0 && ecode > MAXERRORCODE)
   {
      return e_short_text[-1 * ecode];
   }
   else
   {
      sprintf(e_buf,"Unknown Code: %d",ecode);
      return e_buf;
   }
}
