CC = gcc -g -msse2 -mfpmath=sse -funroll-all-loops -ffast-math -lm -lpthread 
DEBUG = -O3
RM = rm
CP = cp
SRCDIR = .
CFLAGS =  $(DEBUG) -c -D IS_LINUX -U IS_WIN32
LDFLAGS = $(DEBUG)

ALL : hrrt_osem3d_span3

hrrt_osem3d_span3 : scanner_model.o  hrrt_osem3dv_sbrt_span3.o nr_utils.o file_io_processor.o simd_operation.o hrrt_osem3d_span3.o mm_malloc.o
	$(CC) $(LDFLAGS) $(LIB) hrrt_osem3d_span3.o nr_utils.o file_io_processor.o simd_operation.o 	hrrt_osem3dv_sbrt_span3.o scanner_model.o mm_malloc.o  -o hrrt_osem3d_span3


hrrt_osem3d_span3.o : $(SRCDIR)/hrrt_osem3d_span3.cpp $(SRCDIR)/hrrt_osem3dv_sbrt_span3.cpp $(SRCDIR)/hrrt_osem3d.h
	$(CC) $(CFLAGS) $(SRCDIR)/hrrt_osem3d_span3.cpp


hrrt_osem3dv_sbrt_span3.o :   $(SRCDIR)/hrrt_osem3dv_sbrt_span3.cpp $(SRCDIR)/hrrt_osem3d.h
	$(CC) $(CFLAGS) $(SRCDIR)/hrrt_osem3dv_sbrt_span3.cpp

file_io_processor.o  :  $(SRCDIR)/file_io_processor.cpp
	$(CC) $(CFLAGS) $(SRCDIR)/file_io_processor.cpp

simd_operation.o  :  $(SRCDIR)/simd_operation.cpp
	$(CC) $(CFLAGS) $(SRCDIR)/simd_operation.cpp

mm_malloc.o  :  $(SRCDIR)/mm_malloc.cpp
	$(CC) $(CFLAGS) $(SRCDIR)/mm_malloc.cpp

nr_utils.o  :  $(SRCDIR)/nr_utils.cpp
	$(CC) $(CFLAGS) $(SRCDIR)/nr_utils.cpp

scanner_model.o : $(SRCDIR)/scanner_model.cpp
	$(CC) $(CFLAGS) $(SRCDIR)/scanner_model.cpp

clean:
	$(RM) hrrt_osem3d_span3 *.o 


depend:
	makedepend -Dunix $(CFLAGS) $(SRCDIR)/*.cpp
# DO NOT DELETE THIS LINE -- make depend depends on it.
