//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DUGUI.rc
//
#define ID_ORDER_BUTTON                 2
#define ID_DESIGNATE                    3
#define IDD_DUGUI_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDR_MENU                        129
#define IDD_CRMEDIT                     130
#define IDD_CRYSTALPEAKS                131
#define IDD_DESIGNATE_PEAKS             132
#define IDD_HEAD_SELECT                 133
#define IDD_ENERGY_RANGE                134
#define IDD_CRYSTAL_TIME                135
#define IDD_LOAD_DIALOG                 136
#define IDD_INFO_DIALOG                 137
#define ID_UNDO                         502
#define ID_SAVE                         503
#define ID_DOWNLOAD                     504
#define IDC_VIEWDROP                    1000
#define IDC_HEADDROP                    1001
#define IDC_CONFIGDROP                  1002
#define IDC_LAYERDROP                   1003
#define IDC_TRANSMISSION_CHECK          1004
#define IDC_ACQUIRE                     1005
#define IDC_ACQUIRE_HEADDROP            1006
#define IDC_ABORT                       1007
#define IDC_AMOUNT                      1008
#define IDC_ACQUIRE_TYPEDROP            1009
#define IDC_SAVE                        1010
#define IDC_ANALYZE                     1011
#define IDC_PMTD                        1012
#define IDC_ACQDATE                     1013
#define IDC_DEFAULTS                    1014
#define IDC_PREVIOUS                    1015
#define IDC_PMTC                        1017
#define IDC_PMTB                        1018
#define IDC_PMTA                        1019
#define IDC_X_OFF                       1020
#define IDC_HEAD_LIST                   1020
#define IDC_Y_OFF                       1021
#define IDC_ARCHIVE_LIST                1021
#define IDC_CFD                         1022
#define IDLOAD                          1022
#define IDC_LOAD_CONFIG                 1023
#define IDC_SHAPE                       1024
#define IDSAVE                          1024
#define IDC_SLOW_LOW                    1025
#define IDDELETE                        1025
#define IDC_SLOW_HIGH                   1026
#define IDC_MESSAGE_LABEL               1026
#define IDC_SLOW                        1027
#define IDC_FAST_LOW                    1028
#define IDC_FAST_HIGH                   1029
#define IDC_BLOCK                       1030
#define IDC_NEXT                        1031
#define IDC_X_POS                       1032
#define IDC_Y_POS                       1033
#define IDC_VALUE                       1034
#define IDC_FAST                        1035
#define IDC_VARIABLE_FIELD              1036
#define IDC_EDIT                        1037
#define IDC_REGION_CHECK                1038
#define IDC_DNL_CHECK                   1039
#define IDC_PEAKS_CHECK                 1040
#define IDC_THRESHOLD_CHECK             1041
#define IDC_MASTER_CHECK                1042
#define IDC_TUBEDROP                    1043
#define IDC_DIVIDER_CHECK               1044
#define IDC_SMOOTH_SLIDER               1045
#define IDC_SMOOTH_LABEL                1046
#define IDC_VARIABLE_LABEL              1047
#define IDC_FAST_DASH                   1048
#define IDC_SLOW_DASH                   1049
#define IDC_CROSSTALK_CHECK             1050
#define IDC_NUMBER_CHECK                1051
#define IDC_SPIN_PEAKS                  1052
#define IDC_DISTANCE                    1053
#define IDC_CROSSTALK_BUTTON            1054
#define IDC_SPIN_EDGE                   1055
#define IDC_COUNT                       1055
#define IDC_EDGE_DISTANCE               1056
#define IDC_SELECT0                     1056
#define IDC_EDGE_BUTTON                 1057
#define IDC_PROGRESS                    1057
#define IDRESET                         1058
#define IDC_SELECT_ALL                  1058
#define IDC_SMOOTH_SPIN                 1060
#define IDC_SMOOTH_TEXT                 1061
#define IDC_PEAK_TEXT                   1062
#define IDC_CRYSTAL_TEXT                1063
#define IDC_VIEWDROP_RANGE              1063
#define IDC_LLD                         1064
#define IDC_LLD_SPIN                    1064
#define IDC_ULD                         1065
#define IDC_CRYSTALTEXT                 1065
#define IDC_LLD_TEXT                    1065
#define IDC_OFFSET_TEXT                 1066
#define IDC_PROGRESS_LABEL              1066
#define IDC_ULD_SPIN                    1066
#define IDC_VIEW_LABEL                  1067
#define IDC_ULD_TEXT                    1067
#define IDC_CONFIG_LABEL                1068
#define IDC_ACQUISITION_LABEL           1069
#define IDC_GAIN_LABEL                  1070
#define IDC_D_LABEL                     1071
#define IDC_SELECT2                     1072
#define IDC_B_LABEL                     1072
#define IDC_SELECT3                     1073
#define IDC_XOFF_LABEL                  1073
#define IDC_SELECT4                     1074
#define IDC_CFD_LABEL                   1074
#define IDC_SELECT5                     1075
#define IDC_DISPLAY_LABEL               1075
#define IDC_SELECT6                     1076
#define IDC_LAYER_LABEL                 1076
#define IDC_SELECT7                     1077
#define IDC_AMOUNT_LABEL                1077
#define IDC_SELECT8                     1078
#define IDC_UNITS_LABEL                 1078
#define IDC_SELECT9                     1079
#define IDC_C_LABEL                     1079
#define IDC_SELECT10                    1080
#define IDC_A_LABEL                     1080
#define IDC_SELECT11                    1081
#define IDC_YOFF_LABEL                  1081
#define IDC_SELECT12                    1082
#define IDC_SHAPE_LABEL                 1082
#define IDC_SELECT13                    1083
#define IDC_X_LABEL                     1083
#define IDC_SELECT14                    1084
#define IDC_Y_LABEL                     1084
#define IDC_SELECT15                    1085
#define IDC_VALUE_LABEL                 1085
#define IDC_STATIC_MSG                  1086
#define IDC_SELECT1                     1087
#define IDC_BUTTON1                     1087
#define ID_FILE_EXIT                    32771
#define ID_DOWNLOAD_CRMS                32778
#define ID_ACQUIRE_MASTER_TUBE_ENERGY   32779
#define ID_SET_ENERGY_RANGE             32780
#define ID_FILE_ARCHIVE                 32781
#define ID_FILE_DOWNLOADCRYSTALENERGY   32782
#define ID_FILE_DIAGNOSTICS             32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
