//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ScanIt.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SCANIT_FORM                 101
#define IDR_MAINFRAME                   128
#define IDR_SCANITTYPE                  129
#define ID_INDICATOR_ICON               129
#define IDD_GRAPH_PROP                  130
#define IDD_SYSTEM_CONFIG               131
#define IDD_CONFIG_DLG                  133
#define IDD_COMMUNICATION               135
#define IDI_ICON1                       138
#define IDI_ICON2                       139
#define IDI_ICON3                       140
#define IDI_ICON4                       141
#define IDI_ICON5                       142
#define IDI_ICON6                       151
#define IDI_ICON7                       152
#define IDI_ICON8                       153
#define IDI_ICON9                       154
#define IDI_ICON10                      155
#define IDI_ICON11                      156
#define IDI_ICON12                      157
#define IDI_ICON13                      158
#define IDI_ICON14                      159
#define IDD_PATIENT_INFO                160
#define IDI_ICON15                      162
#define IDI_ICON16                      165
#define IDI_ICON17                      166
#define IDI_ICON18                      167
#define IDD_DIALOG1                     169
#define IDD_DOSAGE_INFO                 169
#define IDD_DIAGNOSTIC                  170
#define IDI_ICON19                      174
#define IDC_EDIT_STAT                   1000
#define IDC_EDIT_STRENGTH               1000
#define IDC_BTN_START                   1001
#define IDC_EDIT_CLR_RNDMS              1001
#define IDC_EDIT_SCAN                   1001
#define IDC_BTN_ABORT                   1002
#define IDC_SPIN1                       1002
#define IDC_COMBO1                      1003
#define IDC_CHECK_RANDOMS               1003
#define IDC_EDIT_CLR_PRMPTS             1004
#define IDC_RADIO_EM                    1004
#define IDC_SPIN2                       1005
#define IDC_RADIO_TX                    1005
#define IDC_COMBO_STRENGTH              1005
#define IDC_EDIT_HD                     1006
#define IDC_CHECK_TRUES                 1006
#define IDC_RADIO_SCAN_MODE             1006
#define IDC_EDIT_ROWS                   1007
#define IDC_EDIT_CLR_RNDMS2             1007
#define IDC_RADIO_SCAN_HST              1007
#define IDC_COMBO_COM                   1007
#define IDC_EDIT_COLS                   1008
#define IDC_EDIT_CLR_PRMPTS2            1008
#define IDC_RADIO_BAUD                  1008
#define IDC_EDIT_CNFG                   1009
#define IDC_RADIO_BAUD2                 1009
#define IDC_CHECK_MOVE                  1009
#define IDC_CHECK_HD0                   1010
#define IDC_RADIO_BAUD3                 1010
#define IDC_CHECK_HD1                   1011
#define IDC_RADIO_BAUD4                 1011
#define IDC_CHECK_HD2                   1012
#define IDC_RADIO_PARITY                1012
#define IDC_CHECK_HD3                   1013
#define IDC_EDIT_SINGLES                1013
#define IDC_RADIO_PARITY2               1013
#define IDC_CHECK_HD4                   1014
#define IDC_EDIT_RANDOMS                1014
#define IDC_EDIT_LLD                    1014
#define IDC_RADIO_DATA                  1014
#define IDC_CHECK_HD5                   1015
#define IDC_EDIT_PROMPTS                1015
#define IDC_EDIT_ULD                    1015
#define IDC_RADIO_PARITY3               1015
#define IDC_CHECK_HD6                   1016
#define IDC_EDIT_TIME                   1016
#define IDC_STATIC_LLD                  1016
#define IDC_RADIO_DATA2                 1016
#define IDC_CHECK_HD7                   1017
#define IDC_EDIT_DURATION               1017
#define IDC_RADIO_STOP                  1017
#define IDC_EDIT_TOT_RNDS               1017
#define IDC_RADIO_STOP2                 1018
#define IDC_EDIT_LAST_NAME              1018
#define IDC_EDIT_TOT_TRS                1018
#define IDC_EDIT_WORJ_DIR               1018
#define IDC_EDIT_PLANE                  1019
#define IDC_EDIT_FIRST_NAME             1019
#define IDC_EDIT_TIME_REMAIN            1019
#define IDC_EDIT_NORM_FILE              1019
#define IDC_EDIT_SPAN                   1020
#define IDC_EDIT_DOB                    1020
#define IDC_EDIT_TOTAL_EVENTS           1020
#define IDC_EDIT_BLANK_FILE             1020
#define IDC_EDIT_RING                   1021
#define IDC_RADIO_SEX                   1021
#define IDC_EDIT_CAL_FACTOR             1021
#define IDC_EDIT_PATIENT_NAME           1021
#define IDC_EDIT_SCANNER_TYPE           1021
#define IDC_EDIT_YMIN_MAN               1022
#define IDC_STATIC_ULD                  1022
#define IDC_RADIO_SEX2                  1022
#define IDC_EDIT_YMAX_MAN               1023
#define IDC_STATIC_SPD_DUR              1023
#define IDC_RADIO_SEX3                  1023
#define IDC_EDIT_YMIN_EXP               1024
#define IDC_STATIC_PLN                  1024
#define IDC_EDIT_FIRST_NAME2            1024
#define IDC_EDIT_PATIENT_ID             1024
#define IDC_EDIT_YMAX_EXP               1025
#define IDC_STATIC_SPN                  1025
#define IDC_COMBO_ISO                   1025
#define IDC_STATIC_RNG                  1026
#define IDC_LIST1                       1026
#define IDC_EDIT_MOVE                   1026
#define IDC_SPIN_YMIN                   1027
#define IDC_EDIT_SPEED                  1027
#define IDC_LN_SEARCH                   1027
#define IDC_SPIN_YMAX                   1028
#define IDC_FN_SEARCH                   1028
#define IDC_EDIT_SINO                   1028
#define IDC_RADIO_LIN                   1029
#define IDC_DOB_SEARCH                  1029
#define IDC_EDIT1                       1029
#define IDC_RADIO_LOG                   1030
#define IDC_ID_SEARCH                   1030
#define IDC_BUTTON_DIR                  1030
#define IDC_EDIT_AC_KCPS                1030
#define IDC_SEARCH_ALL                  1031
#define IDC_BUTTON_NORM                 1031
#define IDC_BUTTON_BLANK                1032
#define IDC_BUTTON0_RPT                 1033
#define IDC_BUTTON4_RPT                 1034
#define IDC_CHECK1                      1034
#define IDC_BUTTON1_RPT2                1035
#define IDC_BUTTON1_RPT                 1035
#define IDC_BUTTON2_RPT                 1036
#define IDC_RADIO_COUNT                 1036
#define IDC_BUTTON3_RPT                 1037
#define IDC_RADIO_COUNT_RP              1037
#define IDC_BUTTON5_RPT                 1038
#define IDC_RADIO_PRESET                1038
#define IDC_BUTTON6_RPT                 1039
#define IDC_RADIO_PRESET_CNT            1039
#define IDC_BUTTON7_RPT                 1040
#define IDC_CHECK2                      1040
#define IDC_CHECK_NAME                  1041
#define IDC_CHECK3                      1041
#define IDC_CHECK_PID                   1042
#define IDC_CHECK_CID                   1043
#define IDC_CHECK_NUM                   1044
#define IDC_CHECK4                      1045
#define IDC_CHECK5                      1046
#define IDC_BUTTON1                     1047
#define IDC_BUTTON2                     1048
#define IDC_EDIT_UPFILE                 1049
#define IDC_EDIT2                       1050
#define IDC_EDIT_SOURCE_NAME            1050
#define IDC_BUTTON3                     1051
#define IDC_BUTTON4                     1052
#define IDC_BUTTON_DOS                  1052
#define IDC_BUTTON_RESET                1053
#define IDC_BUTTON_ID                   1054
#define IDC_BUTTON_PID                  1055
#define IDC_BUTTON_ASD                  1056
#define IDC_BUTTON_LPE                  1057
#define IDC_EDIT_DOS                    1058
#define ID_SETUP_SYS_CONFIG             32772
#define ID_CONTROL_CONFIG               32773
#define ID_PROCESS_START                32790
#define ID_PROCESS_ABORT                32791
#define ID_PROCESS_STOP                 32793
#define ID_SETUP_COM                    32794
#define ID_SETUP_GRAPH_PROP             32795
#define ID_CONTROL_PATIENT              32796
#define ID_POST_RECON                   32798
#define ID_POST_NORM                    32799
#define ID_POST_ATTEN                   32800
#define ID_HELP_TOPIC                   32804
#define ID_DIAGNOSTIC_SHOW              32805
#define ID_DOSAGE_INFO                  32806
#define ID_SPACE                        32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
